---
ip_nodo1: 192.168.56.101

ip_nodo2: 192.168.56.102

dns_zone: juanpe.org

dns_zone_ip: 56.168.192

cname_drupal: www

packages_nodo1:
  - postgresql-9.6
  - python-psycopg2
  - bind9

packages_nodo2:
  - apache2
  - php7.0
  ## Paquetes para pruebas
  - postgresql-client-9.6
  - dnsutils

db_paramaters:
  name: drupal_db
  user: drupal_user
  passwd: drupal
...