---
- name: Configuración virtualhost drupal
  template:
    src: drupal.conf.j2
    dest: /etc/apache2/sites-available/drupal.conf
    owner: root
    group: root
    mode: 0644

- name: Habilitar virtualhost
  shell: a2ensite drupal.conf

- name: Habilitar módulo rewrite
  apache2_module:
    state: present
    name: rewrite
  notify:
    Reiniciar Apache2
...