---
- hosts: all
  name: Actualización inicial
  roles:
    - common

- hosts: nodo1
  name: Configuración nodo1
  pre_tasks:
  - name: Instalar Postgresql y Bind9
    apt:
      name: "{{ packages_nodo1 }}"
      state: latest
  roles:
    - bind9
    - postgresql

- hosts: nodo2
  name: Configuración nodo2
  pre_tasks:
  - name: Instalar Apache2 y PHP
    apt:
      name: "{{ packages_nodo2 }}"
      state: latest
#  roles:
#    - apache2
#    - drupal
...