---
- name: Permitir conexiones
  replace:
    dest: /etc/postgresql/9.6/main/postgresql.conf
    regexp: '.*listen_addresses.*'
    replace: "listen_addresses = '*'"

- name: Permitir conexiones local y con nodo2
  template:
    src: pg_hba.j2
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
## No ejecuta el handler despues del task(lo hace después del play completo) así que ejecuto reinicio postres manual
#  notify:
#    Reiniciar Postgresql

- name: Reiniciar Postgres
  systemd:
    name: postgresql
    state: restarted

- name: Creación base de datos
  become_user: postgres
  postgresql_db:
    name={{ db_paramaters['name'] }}
    #name=prueba1

- name: Creación usuario
  become_user: postgres
  postgresql_user:
    db={{ db_paramaters['name'] }}    
    name={{ db_paramaters['user'] }}    
    password={{ db_paramaters['passwd'] }}    
    priv=ALL
    #db=prueba1
    #name=user1
    #password=user

- name: Habilitar "bytea_output" a "escape"
  become_user: postgres
  shell: psql -c "ALTER DATABASE \"{{ db_paramaters['name'] }}\" SET bytea_output = 'escape';"
...