---
- name: Creación carpeta drupal
  file:
    path: /var/www/drupal
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Descargar drupal
  unarchive:
    src: https://www.drupal.org/download-latest/tar.gz
    dest: /var/www/drupal
    owner: www-data
    group: www-data
    remote_src: yes
    extra_opts: [--strip-components=1]
...